tinyMCE.addI18n('en.advanced',{
style_select:"Styl",
font_size:"Velikost písma",
fontdefault:"Písmo",
block:"Formát textu",
paragraph:"Výchozí",
div:"Div",
address:"Addresa",
pre:"Předformátovaný",
h1:"Nadpis 1",
h2:"Nadpis 2",
h3:"Nadpis 3",
h4:"Nadpis 4",
h5:"Nadpis 5",
h6:"Nadpis 6",
blockquote:"Blok citace",
code:"Kód",
samp:"Ukázka kódu",
dt:"Definice termínu ",
dd:"Popis definice",
bold_desc:"Tučně (Ctrl+B)",
italic_desc:"Kurzíva (Ctrl+I)",
underline_desc:"Podtržení (Ctrl+U)",
striketrough_desc:"Přeškrtnutí",
justifyleft_desc:"Zarovnání vlevo",
justifycenter_desc:"Zarovnání na střed",
justifyright_desc:"Zarovnání vpravo",
justifyfull_desc:"Do bloku",
bullist_desc:"Seznam",
numlist_desc:"Číslovaný seznam",
outdent_desc:"Zmenšit odsazení",
indent_desc:"Zvětšit odsazení",
undo_desc:"Zpět (Ctrl+Z)",
redo_desc:"Vpřed (Ctrl+Y)",
link_desc:"Vložit/editovat odkaz",
unlink_desc:"Odebrat odkaz",
image_desc:"Vložit/editovat obrázek",
cleanup_desc:"Vyčistit kód",
code_desc:"Editovat HTML kód",
sub_desc:"Dolní index",
sup_desc:"Horní index",
hr_desc:"Vložit vodorovnou čáru",
removeformat_desc:"Zrušit formátování textu",
custom1_desc:"Vlastní popis zde",
forecolor_desc:"Barva písma",
backcolor_desc:"Barva pozadí písma",
charmap_desc:"Vložit znak",
visualaid_desc:"Zobrazit nebo skrýt neviditelné prvky",
anchor_desc:"Vložit / změnit záložku",
cut_desc:"Vyjmout",
copy_desc:"Kopírovat",
paste_desc:"Vložit",
image_props_desc:"Nastavení obrázku",
newdocument_desc:"Nový dokument",
help_desc:"Nápověda",
blockquote_desc:"Blok citace",
clipboard_msg:"Kopírovat / Vyjmout / Vložit nejsou dostupné v Mozille a Firefoxu.\r\nChcete více informací o tomto problému?",
path:"Cesta",
newdocument:"Jste si jisti, že chcete vymazat veškerý obsah?",
toolbar_focus:"Přejít na nástrojovou lištu - Alt + Q, přejít do editoru - Alt-Z, přejít na element - Alt-X",
more_colors:"Více barev",

// Accessibility Strings
shortcuts_desc:'Dostupná nápověda',
help_shortcut:'. Stiskni ALT F10 pro nástrojovou lištu. Stiskni ALT 0 pro nápovědu.',
rich_text_area:"Textová oblast",
toolbar:"Nástrojová lišta"
});
