tinyMCE.addI18n('en.advanced_dlg',{
about_title:"O TinyMCE",
about_general:"O programu",
about_help:"Nápověda",
about_license:"Licence",
about_plugins:"Pluginy",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Verze",
about_loaded:"Nečtené pluginy",
anchor_title:"Vložit / změnit záložku",
anchor_name:"Jméno záložky",
anchor_invalid:"Zadejte prosím platný název záložky.",
code_title:"HTML editor",
code_wordwrap:"Zalamování řádků",
colorpicker_title:"Výběr barvy",
colorpicker_picker_tab:"Výběr",
colorpicker_picker_title:"Výběr barvy",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta barev",
colorpicker_named_tab:"Pojmenované",
colorpicker_named_title:"Pojmenované barvy",
colorpicker_color:"Barva:",
colorpicker_name:"Jméno:",
charmap_title:"Vyberte speciální znak",
image_title:"Vložit/editovat obrázek",
image_src:"URL obrázku",
image_alt:"Popis obrázku",
image_list:"Seznam obrázků",
image_border:"Rámeček",
image_dimensions:"Rozměry",
image_vspace:"Vertikální mezera",
image_hspace:"Horizontální mezera",
image_align:"Obtékání",
image_align_baseline:"Základní",
image_align_top:"Nahoře",
image_align_middle:"Na střed",
image_align_bottom:"Dole",
image_align_texttop:"Text nahoře",
image_align_textbottom:"Text dole",
image_align_left:"Vlevo",
image_align_right:"Vpravo",
link_title:"Vložit/editovat odkaz",
link_url:"URL odkazu",
link_target:"Cíl",
link_target_same:"Otevřít odkaz ve stejném okně",
link_target_blank:"Otevřít odkaz v novém okně",
link_titlefield:"Titulek",
link_is_email:"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?",
link_is_external:"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?",
link_list:"Seznam odkazů",
accessibility_help:"Dostupná nápověda",
accessibility_usage_title:"Všeobecné použití"
});